create table if not exists public.remindiq_feedback_items (
  id bigint generated by default as identity primary key,
  feedback_id text unique not null,
  created_at timestamptz not null,
  tester_id text,
  issue_type text,
  comment text,
  conversation jsonb,
  active_draft jsonb,
  visible_reminders_snapshot jsonb,
  app_url text,
  user_agent text,
  source text,
  sync_status text,
  synced_at timestamptz,
  sync_error text,
  build_label text,
  app_version text,
  platform text,
  native_shell boolean default false
);

alter table public.remindiq_feedback_items enable row level security;

drop policy if exists "Allow anonymous inserts for feedback" on public.remindiq_feedback_items;
create policy "Allow anonymous inserts for feedback"
on public.remindiq_feedback_items
for insert
to anon
with check (true);

drop policy if exists "Allow authenticated reads for feedback" on public.remindiq_feedback_items;
create policy "Allow authenticated reads for feedback"
on public.remindiq_feedback_items
for select
to authenticated
using (true);
